# Step 1, build json
FROM golang:1.14.1 AS build-server

WORKDIR /app

COPY ./go.mod ./go.sum /app/
RUN go mod download

COPY . /app/

RUN go build -o /app/main ./cmd/loader/main.go

RUN chmod +x /app/main

RUN /app/main

# Step 2, build client
FROM node:13.12.0 AS webpack-build

WORKDIR /app

RUN npm install --force -g yarn

COPY ./client/package.json ./client/yarn.lock /app/
RUN yarn

COPY ./client /app/
COPY --from=build-server /app/client/src/data/*.json /app/src/data/

RUN npm run-script build

RUN git config --global user.email "theadam4257@gmail.com"
RUN git config --global user.name "Adam Nalisnick"

CMD node_modules/.bin/gh-pages -f -d build --repo git@github.com:theadam/covid-data.git 2>&1
