version: '3.7'
services:
  covid-server:
    container_name: covid-server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/covid?sslmode=disable
      - PORT=8080

  covid-client:
    container_name: covid-client
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - covid-server
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=covid
      - DATABASE_HOST=postgres


