version: '3.7'
services:
  covid-server:
    container_name: covid-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app

  covid-client:
    container_name: covid-client
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - covid-server
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
