version: '3.7'
services:
  covid-server:
    container_name: covid-server
    build:
      context: .
      dockerfile: Dockerfile-prod
    depends_on:
      - postgres
    ports:
      - '8080:8080'

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=covid
      - DATABASE_HOST=postgres


